# for local development
version: '3.7'
networks:
  network-custom:
    name: 3afoods_frontend
    external: true
services:
  quasar-admin:
    container_name: 3afoods-web-prod
    build:
      context: .
    ports:
      - "${NGINX_HOST_PORT}:80"
    networks:
      - network-custom
